name: Greeting Bot

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        uses: actions/github-script@v6
        with:
          script: |
            const greetingMessage = "Hi there! Thanks for your contribution. We'll review it soon.";
            if (github.context.issue) {
              await github.rest.issues.createComment({
                issue_number: github.context.issue.number,
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                body: greetingMessage
              });
            } else if (github.context.payload.pull_request) {
              await github.rest.issues.createComment({
                issue_number: github.context.payload.pull_request.number,
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                body: greetingMessage
              });
            }
