name: Code Scanner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

# codeQL

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/setup@v2
        with:
          languages: python, javascript # Adapte para as linguagens do seu projeto

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

# Safety for python scripts

  safety:
    name: Safety Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install safety

      - name: Run Safety
        run: |
          safety check

# End of file

      - name: End of file
        run: |
          echo Made by ruisuan for CyonicSolutions
