name: Translate License

on:
  push:
    paths:
      - 'license.md'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install googletrans==4.0.0-rc1

    - name: Run translation script
      run: python ./scripts/translate.py

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Create or Checkout Branch
      run: |
        git fetch origin
        git checkout -B update-translations origin/update-translations || git checkout -b update-translations

    - name: Commit translations
      run: |
        git add licenses/
        git commit -m "Automation: Update translated license files" || echo "No changes to commit"

    - name: Push branch
      run: |
        git push --set-upstream origin update-translations

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v4
      with:
        title: 'Automation: Update Translations'
        body: 'This PR updates the translated license files. Please review and merge.'
        base: main
        branch: update-translations

    - name: Lock PR comments
      uses: actions/github-script@v6
      with:
        script: |
          const pullRequestNumber = '${{ steps.create_pr.outputs.pull-request-number }}'; // Obtém o número da PR do passo anterior
          const repo = context.repo.repo;
          const owner = context.repo.owner;

          if (!pullRequestNumber) {
            throw new Error('Pull Request number is undefined');
          }

          // Lock comments on the PR (note: locking comments is not directly supported, this will only close the PR as an example)
          await github.rest.pulls.update({
            owner: owner,
            repo: repo,
            pull_number: pullRequestNumber,
            state: 'closed'
          });

          console.log(`PR #${pullRequestNumber} is now closed`);
